
export type Riddle = {
  riddle: string;
  answer: number;
};

// Add up to 50 riddles here
export const riddles: Riddle[] = [
  { riddle: "I am an odd number. Take away one letter and I become even. What number am I?", answer: 7 },
  { riddle: "What is half of two plus two?", answer: 3 },
  { riddle: "A grandmother, two mothers, and two daughters went to a baseball game. They bought one ticket each. How many tickets did they buy in total?", answer: 3 },
  { riddle: "How many sides does a circle have?", answer: 2 },
  { riddle: "Using only addition, how can you add eight 8s to get the number 1,000?", answer: 888 + 88 + 8 + 8 + 8 },
  { riddle: "What is the next number in the sequence: 1, 4, 9, 16, 25, ...?", answer: 36 },
  { riddle: "If a hen and a half lay an egg and a half in a day and a half, how many eggs will half a dozen hens lay in half a dozen days?", answer: 24 },
  { riddle: "I am a three-digit number. My second digit is 4 times bigger than the third digit. My first digit is 3 less than my second digit. What number am I?", answer: 141 },
  { riddle: "If you multiply this number by any other number, the answer will always be the same. What number is this?", answer: 0 },
  { riddle: "There are 10 apples. You take away 4. How many do you have?", answer: 4 },
  { riddle: "What is 5 x 4?", answer: 20 },
  { riddle: "There are 12 fish in a tank. 5 of them drown. How many are left?", answer: 12 },
  { riddle: "A farmer has 17 sheep and all but 9 die. How many are left?", answer: 9 },
  { riddle: "How many months have 28 days?", answer: 12 },
  { riddle: "What is the sum of the numbers on a standard die?", answer: 21 },
  { riddle: "A man is twice as old as his son. 20 years ago, he was 12 times the age of his son. What is the present age of the father?", answer: 44 },
  { riddle: "What number do you get when you multiply all of the numbers on a telephone's number pad?", answer: 0 },
  { riddle: "What is the next number in the series? 7, 10, 8, 11, 9, 12, ...", answer: 10 },
  { riddle: "A shirt and a tie cost $50. The shirt costs $30 more than the tie. How much does the tie cost?", answer: 10 },
  { riddle: "If 3 cats can catch 3 mice in 3 minutes, how long will it take 100 cats to catch 100 mice?", answer: 3 },
  { riddle: "I have two coins totaling 55 cents. One is not a nickel. What are the two coins?", answer: 50 },
  { riddle: "What is the next prime number after 13?", answer: 17 },
  { riddle: "If it takes 8 men 10 hours to build a wall, how long would it take 4 men?", answer: 20 },
  { riddle: "How many times can you subtract the number 5 from 25?", answer: 1 },
  { riddle: "You are given a telephone and asked to multiply all the numbers on the device’s number pad. What will be the answer?", answer: 0 },
  { riddle: "The total of my digits is 5. I am an even number. I am greater than 30 but less than 50. What number am I?", answer: 32 },
  { riddle: "What is the product of 15 and 4?", answer: 60 },
  { riddle: "If a train travels 1 mile and then half the remaining distance, and so on, what's the total distance it travels?", answer: 2 },
  { riddle: "What number is 40% of 200?", answer: 80 },
  { riddle: "A boy has as many sisters as brothers, but each sister has only half as many sisters as brothers. How many brothers and sisters are there in the family?", answer: 4 },
  { riddle: "What comes next in the sequence: 47, 44, 40, 37, ...?", answer: 33 },
  { riddle: "If two’s company, and three’s a crowd, what are four and five?", answer: 9 },
  { riddle: "What is the number of parking space covered by the car in the image?", answer: 87 },
  { riddle: "What is 1/2 of 1/4 of 1/8 of 4096?", answer: 8 },
  { riddle: "If you were born 5 years ago, how old would you be in 10 years?", answer: 15 },
  { riddle: "There is a basket containing 5 apples, how do you divide the apples among 5 children so that each child has an apple and one apple remains in the basket?", answer: 4 },
  { riddle: "If there are 4 apples and you take away 3, how many do you have?", answer: 3 },
  { riddle: "I am a number that has more than 3 letters. I am an odd number. Take away a letter from my name, and I become even. Who am I?", answer: 7 },
  { riddle: "Which number is the equivalent to 3^4?", answer: 81 },
  { riddle: "What is the value of Pi to two decimal places?", answer: 3.14 },
  { riddle: "What is the square root of 144?", answer: 12 },
  { riddle: "If a car travels at 60 mph, how long will it take to travel 180 miles?", answer: 3 },
  { riddle: "What is 15% of 300?", answer: 45 },
  { riddle: "A pizza is cut into 8 slices. If you eat 3, what fraction of the pizza is left?", answer: 5 },
  { riddle: "What is the value of X if 2X + 5 = 15?", answer: 5 },
  { riddle: "How many degrees are in a right angle?", answer: 90 },
  { riddle: "What is the next number in the Fibonacci sequence: 0, 1, 1, 2, 3, 5, 8, 13, ...?", answer: 21 },
  { riddle: "If you have a pie and cut it into 4 pieces, and then you cut each piece in half, how many pieces do you have?", answer: 8 },
  { riddle: "What is 7 multiplied by 8?", answer: 56 },
  { riddle: "A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?", answer: 5 }
];
